[package]
name = "day-02-rust"
version = "0.1.0"
authors = ["Jakob Erzar <jakob.erzar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.4"